# Generated by Django 6.0.1 on 2026-01-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum venue capacity for this event'),
        ),
    ]
